version: '3.1'

services:
  db:
    container_name: post2
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: somepassword
      POSTGRES_USER: postgres
    ports:
      - '5433:5432'
